[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    unit: mark a test as a unit test
    integration: mark a test as an integration test
    performance: mark a test as a performance test
    security: mark a test as a security test
    slow: mark a test as slow running
    quick: mark a test as quick running
addopts = --verbose --cov=backend --cov-report=term --cov-report=xml --cov-report=html
asyncio_mode = auto
filterwarnings =
    ignore:Support for class-based `config` is deprecated:DeprecationWarning
    ignore:The event_loop fixture provided by pytest-asyncio has been redefined:DeprecationWarning 